name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trans-med-api-ptin:latest
      -
        name: Pull cloud instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_CLOUD }}
          script: ${{ secrets.SSH_COMMAND_UPDATE_API_CLOUD }}
      -
        name: Reload cloud instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_CLOUD }}
          script: ${{ secrets.SSH_COMMAND_RELOAD_API_CLOUD }}
      -
        name: Pull edge instance 0
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_EDGE }}
          script: ${{ secrets.SSH_COMMAND_UPDATE_API_EDGE0 }}
      -
        name: Pull edge instance 1
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_EDGE }}
          script: ${{ secrets.SSH_COMMAND_UPDATE_API_EDGE1 }}
      -
        name: Pull edge instance 1
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_EDGE }}
          script: ${{ secrets.SSH_COMMAND_UPDATE_API_EDGE2 }}
      -
        name: Reload edge 0 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_EDGE }}
          script: ${{ secrets.SSH_COMMAND_RELOAD_API_EDGE0 }}
      -
        name: Reload edge 1 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_EDGE }}
          script: ${{ secrets.SSH_COMMAND_RELOAD_API_EDGE1 }}
      -
        name: Reload edge 2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_EDGE }}
          script: ${{ secrets.SSH_COMMAND_RELOAD_API_EDGE2 }}
